### ISSUE TITLE
ReflectionTypeLoadException on AppBootstrapper.Configure

### ISSUE THREAD

**Issue by mwpowellhtx** [tgjones/gemini#125]
Hello, I am syncing up with upstream master.

In the latest pull:

```
System.Reflection.ReflectionTypeLoadException was unhandled by user code
  HResult=-2146232830
  Message=Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
  Source=mscorlib
  StackTrace:
       at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
       at System.Reflection.RuntimeModule.GetTypes()
       at System.Reflection.Assembly.GetTypes()
       at System.ComponentModel.Composition.Hosting.AssemblyCatalog.get_InnerCatalog()
       at System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetEnumerator()
       at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
       at Caliburn.Micro.BindableCollection`1.<>c__DisplayClasse.<AddRange>b__d()
       at Caliburn.Micro.XamlPlatformProvider.OnUIThread(Action action)
       at Caliburn.Micro.Execute.OnUIThread(Action action)
       at Caliburn.Micro.BindableCollection`1.AddRange(IEnumerable`1 items)
       at Gemini.AppBootstrapper.Configure() in i:\Source\gemini\src\Gemini\AppBootstrapper.cs:line 31
       at Caliburn.Micro.BootstrapperBase.StartRuntime()
       at Caliburn.Micro.BootstrapperBase.Initialize()
       at Gemini.AppBootstrapper..ctor() in i:\Source\gemini\src\Gemini\AppBootstrapper.cs:line 21
  InnerException: 
```

On:

```C#
AssemblySource.Instance.AddRange(
    directoryCatalog.Parts
        .Select(part => ReflectionModelServices.GetPartType(part).Value.Assembly)
        .Where(assembly => !AssemblySource.Instance.Contains(assembly)));
```

**Comment by tgjones** [comment]
I have moved the SharpDX demo back out into its own csproj.
