### ISSUE TITLE
Error on starting app after Clickonce upgrade

### ISSUE THREAD

**Issue by xtomas** [tgjones/gemini#147]
Hello,

I am successfully using your great framework project in my app. But just after I started to use Clickonce, I realized app crash immediately after upgrade. Here is exception content:

```
System.ComponentModel.Composition.CompositionException: The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) Object reference not set to an instance of an object.

Resulting in: An exception occurred while trying to create an instance of type 'Gemini.Modules.MainMenu.ViewModels.MainMenuViewModel'.

Resulting in: Cannot activate part 'Gemini.Modules.MainMenu.ViewModels.MainMenuViewModel'.
Element: Gemini.Modules.MainMenu.ViewModels.MainMenuViewModel -->  Gemini.Modules.MainMenu.ViewModels.MainMenuViewModel -->  AssemblyCatalog (Assembly="Gemini, Version=0.6.2.0, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot get export 'Gemini.Modules.MainMenu.ViewModels.MainMenuViewModel (ContractName="Gemini.Modules.MainMenu.IMenu")' from part 'Gemini.Modules.MainMenu.ViewModels.MainMenuViewModel'.
Element: Gemini.Modules.MainMenu.ViewModels.MainMenuViewModel (ContractName="Gemini.Modules.MainMenu.IMenu") -->  Gemini.Modules.MainMenu.ViewModels.MainMenuViewModel -->  AssemblyCatalog (Assembly="Gemini, Version=0.6.2.0, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot set import 'Gemini.Modules.Shell.ViewModels.ShellViewModel._mainMenu (ContractName="Gemini.Modules.MainMenu.IMenu")' on part 'Gemini.Modules.Shell.ViewModels.ShellViewModel'.
Element: Gemini.Modules.Shell.ViewModels.ShellViewModel._mainMenu (ContractName="Gemini.Modules.MainMenu.IMenu") -->  Gemini.Modules.Shell.ViewModels.ShellViewModel -->  AssemblyCatalog (Assembly="Gemini, Version=0.6.2.0, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot get export 'Gemini.Modules.Shell.ViewModels.ShellViewModel (ContractName="Gemini.Framework.Services.IShell")' from part 'Gemini.Modules.Shell.ViewModels.ShellViewModel'.
Element: Gemini.Modules.Shell.ViewModels.ShellViewModel (ContractName="Gemini.Framework.Services.IShell") -->  Gemini.Modules.Shell.ViewModels.ShellViewModel -->  AssemblyCatalog (Assembly="Gemini, Version=0.6.2.0, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot set import 'Gemini.Modules.MainWindow.ViewModels.MainWindowViewModel._shell (ContractName="Gemini.Framework.Services.IShell")' on part 'Gemini.Modules.MainWindow.ViewModels.MainWindowViewModel'.
Element: Gemini.Modules.MainWindow.ViewModels.MainWindowViewModel._shell (ContractName="Gemini.Framework.Services.IShell") -->  Gemini.Modules.MainWindow.ViewModels.MainWindowViewModel -->  AssemblyCatalog (Assembly="Gemini, Version=0.6.2.0, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot get export 'Gemini.Modules.MainWindow.ViewModels.MainWindowViewModel (ContractName="Gemini.Framework.Services.IMainWindow")' from part 'Gemini.Modules.MainWindow.ViewModels.MainWindowViewModel'.
Element: Gemini.Modules.MainWindow.ViewModels.MainWindowViewModel (ContractName="Gemini.Framework.Services.IMainWindow") -->  Gemini.Modules.MainWindow.ViewModels.MainWindowViewModel -->  AssemblyCatalog (Assembly="Gemini, Version=0.6.2.0, Culture=neutral, PublicKeyToken=null")

   at System.ComponentModel.Composition.Hosting.CompositionServices.GetExportedValueFromComposedPart(ImportEngine engine, ComposablePart part, ExportDefinition definition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportedValue(CatalogPart part, ExportDefinition export, Boolean isSharedPart)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.CatalogExport.GetExportedValueCore()
   at System.ComponentModel.Composition.Primitives.Export.get_Value()
   at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)
   at System.ComponentModel.Composition.ExportServices.<>c__DisplayClass3`1.<CreateStronglyTypedLazyOfT>b__5()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Gemini.AppBootstrapper.GetInstance(Type serviceType, String key)
   at Caliburn.Micro.BootstrapperBase.DisplayRootViewFor(Type viewModelType, IDictionary`2 settings)
   at Gemini.AppBootstrapper.OnStartup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<_ctor>b__0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Regards,

Tomas

**Comment by tgjones** [comment]
It looks like the original exception is `Object reference not set to an instance of an object.` Can you provide a stack trace for that exception?

**Comment by xtomas** [comment]
I'm afraid it's the only exception I have found. I'm not able to repeat this exception in other way then on first start after clickonce upgrade. Do you have any idea how to get full stack?

**Comment by tgjones** [comment]
I'm guessing you're not debugging in Visual Studio at the time the exception occurs? Assuming not, the only way would be to log the exception details to a file.

**Comment by xtomas** [comment]
I wrote the exception into Event Log and full content is already posted.

**Comment by tgjones** [comment]
What code did you use to log the error?

**Comment by xtomas** [comment]
```cs
/// <summary>
    /// Interaction logic for App.xaml
    /// </summary>
    public partial class App : Application
    {
        public App() : base()
        {
            Dispatcher.UnhandledException += OnDispatcherUnhandledException;
        }

        void OnDispatcherUnhandledException(object sender, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs e)
        {
            string message = e.Exception.Message.Length < 100
                ? e.Exception.Message
                : e.Exception.Message.Substring(0, 100) + " ...";

            string errorMessage = string.Format("An Dispatcher unhandled exception occurred:\n\n{0}\n\nSee event log for details.", message);

            if (MessageBox.Show(errorMessage, "DispatcherUnhandledError", MessageBoxButton.YesNo, MessageBoxImage.Error) == MessageBoxResult.Yes)
            {

            }
            
            EventLogger.LogError(e.Exception, errorMessage);

            e.Handled = true;
        }
    }

    internal class EventLogger
    {
        static string source = "Application";

        public static void LogError(Exception e, string format, params object[] args)
        {
            EventLog.WriteEntry(source, e.ToString(), EventLogEntryType.Error, 1);
        }

        public static void LogError(object e, string format, params object[] args)
        {
            EventLog.WriteEntry(source, e.ToString(), EventLogEntryType.Error, 1);
        }
    }
```

**Comment by tgjones** [comment]
[There's a blog post here](http://haacked.com/archive/2014/12/09/unwrap-mef-exception/) describing exactly this situation, and it provides a helpful `UnwrapCompositionException` that you should be able to drop into your project.

**Comment by xtomas** [comment]
The original exception is the same but there is new one:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Gemini.Framework.Themes.ThemeManager.SetCurrentTheme(String name)
   at Gemini.Framework.Themes.ThemeManager.<.ctor>b__0(String value)
   at Gemini.Framework.Services.SettingsPropertyChangedEventManager`1.PropertyChangedEventListener`1.ReceiveWeakEvent(Type managerType, Object sender, EventArgs e)
   at System.Windows.WeakEventManager.ListenerList.DeliverEvent(Listener& listener, Object sender, EventArgs args, Type managerType)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(Object sender, PropertyChangedEventArgs args)
   at System.Configuration.ApplicationSettingsBase.OnPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at System.Configuration.ApplicationSettingsBase.Reload()
   at System.Configuration.ApplicationSettingsBase.Upgrade()
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at Gemini.Properties.Settings.get_AutoHideMainMenu()
   at Gemini.Modules.MainMenu.ViewModels.MainMenuViewModel..ctor(IMenuBuilder menuBuilder)
```

**Comment by tgjones** [comment]
Now we're getting somewhere. But it looks like you're using a release build of Gemini (perhaps from NuGet?), so there aren't any line numbers, and I can't guess which line has the `NullReferenceException`. You might need to do a debug build of Gemini from source, and use that version of the Gemini `.dll` and `.pdb` files.

**Comment by xtomas** [comment]
OK, I will try it. It will take a while I guess.

**Comment by tgjones** [comment]
Yep. Sorry, I can't think of any way round that... I don't get this exception, so I'm guessing it's something to do with the way ClickOnce works.

**Comment by xtomas** [comment]
I'm not able to use debug version of gemini. VS says: must be strong signed in order to be marked as a prerequisite

**Comment by tgjones** [comment]
You should be able to strong sign the assembly, and still generate debugging symbols (`.pdb` files), but you might need to modify the project settings to do that. You don't need to actually debug anything - you just need `Gemini.pdb` alongside `Gemini.dll` in your bin folder.

**Comment by OldNo7** [comment]
@tgjones whe you create your nuget packeges you use the ```-Symbols``` option to create a *.Symbols.nupkg 
When you push a Symbols package it goes to symbolsource.org. You can then add ```http://srv.symbolsource.org/pdb/Public``` to ```Symbol file locations``` under Tools->Options->Debugging->Symbols

**Comment by xtomas** [comment]
Hello. Finnally I used pdb file.

```cs
System.NullReferenceException: Object reference not set to an instance of an object.
   at Gemini.Framework.Themes.ThemeManager.SetCurrentTheme(String name) in c:\Projects\gemini\src\Gemini\Framework\Themes\ThemeManager.cs:line 69
   at Gemini.Framework.Themes.ThemeManager.<.ctor>b__12_0(String value) in c:\Projects\gemini\src\Gemini\Framework\Themes\ThemeManager.cs:line 50
   at Gemini.Framework.Services.SettingsPropertyChangedEventManager`1.PropertyChangedEventListener`1.ReceiveWeakEvent(Type managerType, Object sender, EventArgs e) in c:\Projects\gemini\src\Gemini\Framework\Services\SettingsPropertyChangedEventManager.cs:line 50
   at System.Windows.WeakEventManager.ListenerList.DeliverEvent(Listener& listener, Object sender, EventArgs args, Type managerType)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(Object sender, PropertyChangedEventArgs args)
   at System.Configuration.ApplicationSettingsBase.OnPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at System.Configuration.ApplicationSettingsBase.Reload()
   at System.Configuration.ApplicationSettingsBase.Upgrade()
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at Gemini.Properties.Settings.get_AutoHideMainMenu() in c:\Projects\gemini\src\Gemini\Properties\Settings.Designer.cs:line 31
   at Gemini.Modules.MainMenu.ViewModels.MainMenuViewModel..ctor(IMenuBuilder menuBuilder) in c:\Projects\gemini\src\Gemini\Modules\MainMenu\ViewModels\MainMenuViewModel.cs:line 22

```

**Comment by tgjones** [comment]
Thanks! This is the line that causes the crash:

``` csharp
var windowResourceDictionary = Application.Current.MainWindow.Resources.MergedDictionaries[0];
```

It looks like `MainWindow` is null at the time that code is called, after a ClickOnce upgrade.
